<template>
  <main class="main-content">
    <div class="content-container">
      <h1>Cookie Policy</h1>
    <p class="effective-date"><strong>Effective Date:</strong> 14-Oct-2022 | <strong>Last Updated:</strong> 14-Oct-2022</p>
    
    <section class="policy-section">
      <h2>What are cookies?</h2>
      <p>This Cookie Policy explains what cookies are and how we use them, the types of cookies we use i.e, the information we collect using cookies and how that information is used, and how to manage the cookie settings.</p>
      <p>Cookies are small text files that are used to store small pieces of information. They are stored on your device when the website is loaded on your browser. These cookies help us make the website function properly, make it more secure, provide better user experience, and understand how the website performs and to analyze what works and where it needs improvement.</p>
    </section>

    <section class="policy-section">
      <h2>How do we use cookies?</h2>
      <p>As most of the online services, our website uses first-party and third-party cookies for several purposes. First-party cookies are mostly necessary for the website to function the right way, and they do not collect any of your personally identifiable data.</p>
      <p>The third-party cookies used on our website are mainly for understanding how the website performs, how you interact with our website, keeping our services secure, providing advertisements that are relevant to you, and all in all providing you with a better and improved user experience and help speed up your future interactions with our website.</p>
    </section>

    <section class="policy-section">
      <h2>Types of Cookies we use</h2>
      <p>Our website uses both session and persistent cookies for different purposes:</p>
      <ul>
        <li><strong>Essential cookies:</strong> These are necessary for the website to function properly</li>
        <li><strong>Analytics cookies:</strong> These help us understand how visitors interact with our website</li>
        <li><strong>Functional cookies:</strong> These enable enhanced functionality and personalization</li>
      </ul>
    </section>

    <section class="policy-section">
      <h2>Manage cookie preferences</h2>
      <p>You can change your cookie preferences any time by clicking the cookie settings button. This will let you revisit the cookie consent banner and change your preferences or withdraw your consent right away.</p>
      
      <p>In addition to this, different browsers provide different methods to block and delete cookies used by websites. You can change the settings of your browser to block/delete the cookies. Listed below are the links to the support documents on how to manage and delete cookies from the major web browsers:</p>
      
      <ul class="browser-links">
        <li><strong>Chrome:</strong> <a href="https://support.google.com/accounts/answer/32050" target="_blank">https://support.google.com/accounts/answer/32050</a></li>
        <li><strong>Safari:</strong> <a href="https://support.apple.com/en-in/guide/safari/sfri11471/mac" target="_blank">https://support.apple.com/en-in/guide/safari/sfri11471/mac</a></li>
        <li><strong>Firefox:</strong> <a href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox" target="_blank">Firefox Cookie Support</a></li>
        <li><strong>Internet Explorer:</strong> <a href="https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc" target="_blank">IE Cookie Support</a></li>
      </ul>
      
      <p>If you are using any other web browser, please visit your browser's official support documents.</p>
    </section>

    <footer class="policy-footer">
      <p><small>Cookie Policy Generated By <a href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW" target="_blank">CookieYes – Cookie Policy Generator</a>.</small></p>
    </footer>
    </div>
  </main>
</template>

<style scoped>
.main-content {
  background: #f7f7f7;
  padding: 2rem 0;
  min-height: 100%;
}

.content-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 16px rgba(0,0,0,0.1);
}

.content-container h1 {
  color: #2566af;
  font-size: 2.5rem;
  margin-bottom: 2rem;
  text-align: center;
}
.effective-date {
  font-size: 0.9rem;
  color: #666;
  margin-bottom: 2rem;
  padding: 1rem;
  background: #f8f9fa;
  border-left: 4px solid #2566af;
}

.policy-section {
  margin-bottom: 2rem;
  padding-bottom: 1.5rem;
  border-bottom: 1px solid #e0e0e0;
}

.policy-section:last-child {
  border-bottom: none;
}

.policy-section h2 {
  color: #2566af;
  font-size: 1.3rem;
  margin-bottom: 1rem;
}

.policy-section p {
  line-height: 1.6;
  margin-bottom: 1rem;
}

.policy-section ul {
  padding-left: 1.5rem;
  margin-bottom: 1rem;
}

.policy-section li {
  margin-bottom: 0.5rem;
  line-height: 1.6;
}

.browser-links li {
  margin-bottom: 0.75rem;
}

.policy-section a {
  color: #2566af;
  text-decoration: underline;
}

.policy-section a:hover {
  color: #174a7c;
}

.policy-footer {
  margin-top: 3rem;
  padding-top: 2rem;
  border-top: 1px solid #e0e0e0;
  text-align: center;
}

.policy-footer a {
  color: #2566af;
  text-decoration: underline;
}
</style>
